version: '2.1'

services:
  salt-master:
    image: mirceaulinic/salt-master:2019.2.0
    hostname: salt-master
    container_name: salt-master
    environment:
      - LOG_LEVEL
    volumes:
      - ./master:/etc/salt/master
      - ./pillar/:/etc/salt/pillar/
      - ./extmods/:/etc/salt/extmods/
    network_mode: host
  salt-proxy:
    image: mirceaulinic/salt-proxy:2019.2.0
    hostname: ${PROXYID}
    container_name: salt-proxy-${PROXYID}
    volumes:
      - ./proxy:/etc/salt/proxy
    environment:
      - LOG_LEVEL
      - PROXYID
    network_mode: host
